### ISSUE TITLE
Clean up clock formatting

### ISSUE THREAD

**Issue by willgreenberg** [nyu-ossd-s19/tabi-clock#3]
Seems the clock only changes size by changing the bottom margin of the page, I'll see if I can make it respond to the sides as well.

**Comment by dnntrn** [comment]
Note: I used the W3.CSS framework to make the columns. See their documentation here: https://www.w3schools.com/w3css/. They have some built-in responsive feature, but the canvas may break them. Also, consider making clock disappear on mobile size-- analog may be too small to read. we may need to switch to a digital clock at a certain break-point---> see: https://www.w3schools.com/cssref/css3_pr_mediaquery.asp

**Comment by willgreenberg** [comment]
Got it got it, I was wondering where those class names came from. I’ll look into it later today
